version: "3.8"

services:
  classicmap_mysql:
    image: mysql:8.0
    container_name: classicmap_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - classicmap_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classicmap_backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=${RUST_LOG}
      - SQLX_LOG=${SQLX_LOG}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - MODERATOR_EMAILS=${MODERATOR_EMAILS}
      - CLERK_PEM_PUBLIC_KEY=${CLERK_PEM_PUBLIC_KEY}
      - KOPIS_API_KEY=${KOPIS_API_KEY}
    ports:
      - "1037:1037"
    depends_on:
      classicmap_mysql:
        condition: service_healthy
    networks:
      - classicmap_network

networks:
  classicmap_network:
    driver: bridge

volumes:
  mysql_data:
